<a href="https://colab.research.google.com/github/laraib-anwar/pytorchColab/blob/main/modelTensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

torch_2d = torch.randn(3,4)
torch_2d

tensor([[ 2.1311, -0.7527, -0.6695, -1.1821],
        [-0.5482, -2.0967,  0.3977, -1.4333],
        [ 0.3705, -0.5829,  0.7483,  0.5570]])

In [ ]:
torch_3d = torch.zeros(2,3,4)
torch_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
np1 = np.array([1,2,3,4,5])
torch_tensor = torch.tensor(np1)
torch_tensor


tensor([1, 2, 3, 4, 5])

In [ ]:
import torch
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
import torch
tensor_a = torch.tensor([1,2,3,4,5])
tensor_b = torch.tensor([6,7,8,9,10])
torch.add(tensor_a, tensor_b)
torch.sub(tensor_a, tensor_b)
torch.mul(tensor_a, tensor_b)
torch.div(tensor_a, tensor_b)
torch.remainder(tensor_a, tensor_b)
torch.pow(tensor_a, tensor_b)


tensor([      1,     128,    6561,  262144, 9765625])

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [4]:

class Model(nn.Module):
  def __init__ (in_features=4,h1=8,h2=9,out_features=3):
    super().__init__()
    self.fc1 = nn.Linear(in_features, h1)
    self.fc2 = nn.Linear(h1,h2)
    self.out = nn.Linear(h2,out_features)

  def forward(x):
    x = F.relu(self.fc1(x))
    x = F.relu(self.fc2(x))
    x = self.out(x)

    return x

